### register
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "nama": "Hizkia Yogi Rafael",
    "email": "sekutyog@gmail.com",
    "password": "password",
    "telepon": "08123456788",
    "nik": "1234567890123458",
    "id_divisi": 1,
    "id_perusahaan": 1
}

### update user akun
PUT http://localhost:3000/api/users/approve/5
Content-Type: application/json

### login 
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "sekutyog@gmail.com",
    "password": "password"
}

### Get All Users
GET http://localhost:3000/api/users
Content-Type: application/json

### Add New User
POST http://localhost:3000/api/users

{
    "nama": "Malik Aziz Skena",
    "email": "malikskena@gmail.com",
    "password": "password",
    "telepon": "08123456789",
    "nik": "1234567890123456",
    "id_divisi": 1,
    "id_perusahaan": 1
}


### Update User
PUT http://localhost:3000/api/users/5
Content-Type: application/json

{
  "nama": "Yogi Rafael",
  "email": "yogirafael@gmail.com",
  "telepon": "081234569899",
  "nik": "1234567899489",
  "id_divisi": 2,
  "id_perusahaan": 1,
  "approved": 1
}


### Delete User
DELETE http://localhost:3000/api/users/3
Content-Type: application/json

### Get options
GET http://localhost:3000/options


### Get All Barang
GET http://localhost:3000/api/barang

### deleted Barang
DELETE http://localhost:3000/api/barang/7


### Add New Barang
POST http://localhost:3000/api/barang
Content-Type: application/json

{
    "nama_barang": "Laptop",
    "jumlah": 10,
    "id_supplier": 1,
    "id_perusahaan": 1,
    "id_status_barang": 1,
    "tanggal_pembelian_barang": "2024-08-10",
    "lokasi_barang": "Gudang 1",
    "id_kategori": 1,
    "nomor_seri": ["SN123", "SN124", "SN125", "SN126", "SN127", "SN128", "SN129", "SN130", "SN131", "SN132"]
}

### get data utils
http://localhost:3000/options

### Testing Add Barang

POST http://localhost:3000/api/barang
Content-Type: application/json

{
  "nama_barang": "Laptop Dell XPS 13",
  "jumlah": 3,
  "id_supplier": 1,  // ID supplier yang valid
  "id_perusahaan": 1,  // ID perusahaan yang valid
  "id_status_barang": 1,  // 1 untuk 'Tersedia' atau 2 untuk 'Maintenance'
  "tanggal_pembelian_barang": "2024-08-18",
  "lokasi_barang": "Ruang IT",
  "id_kategori": 2,  // ID kategori yang valid
  "nomor_seri": [
    "SN001", "SN002", "SN003"
  ]
}

### update barang
PUT http://localhost:3000/api/barang/3

{
    "nama_barang": "RJ47",
    "id_supplier": 1,
    "id_perusahaan": 1,
    "tanggal_pembelian_barang": "2024-08-10",
    "lokasi_barang": "Gudang 2",
    "id_kategori": 1,
}

### update serial number
PUT http://localhost:3000/api/barang/serial-number/1

{
    "nomor_seri": "SN123456",
    "status_serial": "Maintenance"
}

### get serial number by id
GET http://localhost:3000/api/barang/serial-number/9

### add Serial Number   
POST http://localhost:3000/api/barang/serial-number/11
Content-Type: application/json

{
  "nomor_seri": ["SN123456", "SN654321", "SN789012"]
}

### Create New Peminjaman
POST http://localhost:3000/api/peminjaman/
Content-Type: application/json

{
  "id_user": 1,
  "id_kategori": 2,
  "id_barang": 3,
  "jumlah": 1,
  "tanggal_pinjam": "2024-08-28",
  "tanggal_kembali": "2024-09-05",
  "keterangan": "Peminjaman untuk acara perusahaan"
}

### Get Peminjaman By User
GET http://localhost:3000/api/peminjaman/
Content-Type: application/json




